// import React from "react";
// import { Link } from "react-router-dom";
// import { useNavigate } from "react-router-dom";

// function LTerms_Conditions() {
//   const scrollToSection = (id) => {
//     const element = document.getElementById(id);
//     if (element) {
//       element.scrollIntoView({ behavior: "smooth" });
//     }
//   };
//   const navigate = useNavigate();  // Initialize the navigate function

//   // Handle button click to navigate back to the home page
//   const handleBackToHome = () => {
//     navigate("/");  // Navigate to the home page
//   };

//   return (
//     <>
//       <div className="container-fluid terms_condition">
//         <div className="terms_condition_header">
//           <div className="terms-image-container">
//             <div className="image-overlay">
//               <h1>Terms and Condition</h1>

//               <a onClick={handleBackToHome} className="termsbutton">Back to Home Page</a>
//             </div>
//           </div>
//         </div>
//       </div>
//       <div className="terms_condition_container">
//         <div className="terms-container">
//         <p>Effective Date: 06-12-2024</p>
//           <p>
//             You have accessed our app (App) and/or our Website
//             www.chalokhelne.com (Website). The domain name Chalo Khelne is owned
//             by Bhalchandraya Innovative Services Private Limited, a private
//             company incorporated under the (Indian) Companies Act, 2013 bearing
//             CIN U72900PN2022PTC211674 and its registration number is 211674. The
//             Website and/or App are internet-based portals developed by Baranwal
//             Consultancy and Services.
//           </p>
//           <p>
//             These Terms and Conditions of use (Terms of Use) are between Chalo
//             Khelne and the users who visit us and/or are registered with us, by
//             following our registration process and the users that use our
//             Services as defined hereinafter or any part thereof on and from our
//             Website and/or App (You or Your or Users). It is hereby clarified
//             that the term User shall deem to include all users of the Website,
//             including without limitation users who are browsing, individuals or
//             the family members of the individuals who obtain and/or intend to
//             obtain our services, coaches, academies, service providers,
//             merchants, and/or are in any manner connected with and/or contribute
//             to the use of the Website and/or App and/or the Services provided
//             through it.
//           </p>
//           <p>
//             Please read these Terms of Use carefully before using or registering
//             or accessing any information or Services through the Website and/or
//             App. By using the Website and/or App or any facility or Services
//             provided by the Website and/or App in any manner whatsoever or by
//             merely browsing the Website and/or App, You signify Your acceptance
//             and shall be legally bound by these Terms of Use, along with any
//             amendments made by Chalo Khelne, at its sole discretion and posted
//             and/or updated on the Website and/or App, and the applicable
//             policies which are incorporated herein by way of reference and as
//             amended from time to time. If these Terms of Use conflict with any
//             other document, these Terms of Use will prevail for the purposes of
//             usage of the Website and/or App. If You do not agree to all or any
//             of the Terms of Use, we recommend You to cease Your access to the
//             Website and/or App or use any Services.
//           </p>
//           <p>
//             These Terms of Use are published in accordance with the provisions
//             of Rule 3 (1) of the Information Technology (Intermediaries
//             guidelines) Rules, 2011 that require publishing the privacy policy
//             and terms of use for access or usage of the Website and/or App and
//             is an electronic record in terms of Information Technology Act, 2000
//             and rules thereunder, as applicable, and the amended provisions
//             pertaining to electronic records in various statutes as amended by
//             the Information Technology Act, 2000. This electronic record is
//             generated by a computer system and does not require any physical or
//             digital signatures.
//           </p>
//           <h2>AMENDMENT</h2>
//           <p>
//             Chalo Khelne reserves the right, at its sole discretion, to change,
//             modify, add or remove portions of these Terms of Use, at any time
//             without any prior written notice to You. The revised Terms of Use
//             shall be made available on the Website and/or App. Your use of the
//             Website and/or App and the Services is subject to the most current
//             version of the Terms of Use made available on the Website and/or App
//             at the time of such use. It is Your responsibility to review these
//             Terms of Use periodically for updates/changes. Your continued use of
//             the Website and/or App following the posting of changes will mean
//             that You accept and agree to the revisions. Any new features or
//             tools which are added to the Website and/or App shall also be
//             subject to the Terms of Use.
//           </p>
//           <h2>ELIGIBILITY TO USE</h2>
//           <p>
//             Use of the Website and/or App is available only to persons who can
//             form legally binding contracts under Indian Contract Act, 1872.
//             Persons who are incompetent to contract within the meaning of the
//             Indian Contract Act, 1872 including minors, un-discharged insolvents
//             etc. are not eligible to use the Website and/or App. As a minor if
//             You wish to use the Website and/or App, such use may be made through
//             Your legal guardian or parents who will be deemed to have given
//             their consent to allow any of their minor dependents to use this
//             Website and/or App at the risks and consequences of the legal
//             guardian or parents, as the case may be.
//           </p>
//           <p>
//             Chalo Khelne reserves the right to terminate Your registration
//             and/or refuse to provide You with access to the Website and/or App
//             if it is brought to Chalo Khelne's notice or if it is discovered or
//             if Chalo Khelne has reason to believe that You are incompetent to
//             contract within the meaning of the Indian Contract Act, 1872.
//             Further, Chalo Khelne reserves the right to refuse access to use the
//             Services offered at the Website and/or App to new Users or to
//             suspend and/or terminate access granted to existing and/or
//             registered Users at any time without according any reasons for doing
//             so.
//           </p>
//           <section>
//             <h2>1. Acceptance of Terms</h2>
//             <p>
//               By using Chalo Khelne, you acknowledge that you have read,
//               understood, and agree to be bound by these Terms and Conditions.
//             </p>
//           </section>

//           <section>
//             <h2>2. User Account</h2>
//             <p>
//               You shall have to apply for registration as a User to use our
//               Website and/or App. Chalo Khelne shall provide the Services to You
//               through the Website and/or App only, if You have created an
//               account and are registered with us.
//               <br />
//               . We shall be entitled to ask You to submit certain information
//               (Account Information) that shall qualify the eligibility criterias
//               laid down for registration by Chalo Khelne from time to time. Each
//               registered User will be given a unique registration id/Your name
//               and password. You can even apply for registration through any
//               other login ID and password (including Facebook, Gmail or Yahoo
//               ID) (Account). Chalo Khelne reserves the right to ask the
//               applicant for more information, if necessary. Chalo Khelne may,
//               for reasons it deems necessary, refuse registration of any User
//               and it is clarified that the decision of Chalo Khelne, in this
//               case, shall be final and conclusive. You shall ensure that the
//               Account Information provided by You is complete, true and
//               accurate. If You provide any information that is untrue,
//               inaccurate, not current or incomplete (or becomes untrue,
//               inaccurate, not current or incomplete), or Chalo Khelne has
//               reasonable grounds to suspect that such information is untrue,
//               inaccurate, not current or incomplete, Chalo Khelne has the right
//               to suspend and/or terminate Your Account and refuse any and all
//               current or future use of the Website and/or App (or any portion
//               thereof). However, Chalo Khelne reserves the right to allow
//               restricted access to the Services for unregistered users but in
//               such a case, only few functionalities of the Website and/or App
//               and/or Services may be available for Your use. You shall be
//               responsible for maintaining the confidentiality of the Account
//               Information and restricting access to Your
//               computer/phone/tablet/any other device to prevent unauthorised
//               access to Your Account. You shall be fully responsible for all
//               activities that occur through Your Account. You shall:
//               <br />
//               a) register in Your own name only and all Account Information
//               provided by You will be accurate and up-to-date; b) not pass
//               yourself off as someone else or create multiple and/or false
//               Accounts; c) promptly update any of Your Account Information in
//               case of any change in the same and also update any new Account
//               Information as required by Chalo Khelne to do so; d)) not transfer
//               Your membership/registration to another person; e) immediately
//               notify Chalo Khelne of any unauthorized use of Your Account or any
//               breach of security; f) inform Chalo Khelne immediately if You have
//               reason to believe that Your password is known to someone else or
//               if Your Account is being, or is likely to be, used in an
//               unauthorized manner; g) log out of Your Account at the end of each
//               session.
//             </p>
//             <p>
//               Chalo Khelne shall not be responsible for Your failure to comply
//               with the above. You may be held liable for any loss incurred by
//               Chalo Khelne or any other third party due to any authorized or
//               unauthorized use of Your Account and You shall be responsible to
//               indemnify Chalo Khelne for the same.
//             </p>
//             <p>
//               You can access and administer Your Account by entering the
//               username and password. You can also update Your personal details
//               (including Your Account Information and preferences) by accessing
//               Your Account and making any necessary changes; this will update
//               Your details across all Services of Chalo Khelne. Chalo Khelne
//               would use this information to provide Your recommendations and
//               options related to the Services requested by You. To deactivate
//               Your account, You may follow the instructions given on our Website
//               and/or App or You may contact our customer support team.
//               Incomplete cancellation requests will be deemed invalid and will
//               not be processed. You will be responsible for any payments that
//               arise from Your failure to deactivate Your account.
//             </p>
//           </section>

//           <section>
//             <h2>3. Termination/ Suspension of Account</h2>
//             <p>
//               We reserve the right to terminate or suspend Your Account and/or
//               suspend Your access to the Services under the following
//               circumstances:
//             </p>
//             <ul>
//               <li>
//                 You are in breach of any term or condition of this Terms of Use;
//               </li>
//               <li>
//                 ii. You are in breach of any laws that are applicable to You;
//               </li>
//               <li>
//                 iii. Your use of the Service disrupts our business operations;
//               </li>
//               <li>
//                 iv. You have behaved in a way that is unlawful or brings us into
//                 disrepute.
//               </li>
//             </ul>
//             <p>
//               We may suspend access to the Services or require You to change
//               Your password if we reasonably believe that the Services have been
//               or are likely to be misused, and we will notify You accordingly.
//               Chalo Khelne may constantly monitor the User's Account in order to
//               avoid fraudulent accounts. Users with more than one account or
//               availing our Services fraudulently shall be liable for legal
//               actions under applicable law. We reserve the right to initiate
//               legal proceedings against such persons for fraudulent use of the
//               Website and/or App and any other unlawful acts or omissions in
//               breach of these Terms of Use. In the event of detection of any
//               fraudulent action, prior to initiation of legal actions, we
//               reserve the right to immediately delete such Account. Any
//               termination of Your registration and/or Account or the Services
//               will not affect liability previously incurred by You.
//             </p>
//             <p>
//               If at any time, we notify You that Your access to and/or use of
//               the Website and/or App or Your Account is suspended and/or
//               terminated, You must cease and desist from all such access and/or
//               use immediately.
//             </p>
//           </section>

//           <section>
//             <h2>4. User Obligations</h2>
//             <p>
//               You agree to use the Services, Website and/or App and the content
//               provided therein only for purposes that are permitted by: (a) the
//               Terms of Use; and (b) any applicable law, regulation or generally
//               accepted practices or guidelines in India and under any applicable
//               law of other jurisdictions.
//             </p>
//             <p>
//               You agree to adhere to all limitations on dissemination, use and
//               reproduction of any materials that You access on the Website
//               and/or App. We grant You a limited license to access and make use
//               of our Website and/or App, however the following usages are not
//               permitted:
//             </p>
//             <ul>
//               <li>
//                 a) downloading (other than page caching) or modifying content or
//                 any portion of it, on our App and/or Website, except with our
//                 express written consent;
//               </li>
//               <li>
//                 b) any resale or commercial use, except as provided hereunder
//                 and agreed between Chalo Khelne and You;
//               </li>
//               <li>
//                 c) downloading or using other User's content without Chalo
//                 Khelne's prior written consent;
//               </li>
//               <li>
//                 d) any collection and use of any content, descriptions; any
//                 derivative use of Website and/or App or its contents;
//               </li>
//               <li>
//                 e) any downloading or copying of Account information for the
//                 benefit of another person.
//               </li>
//             </ul>
//             <p>
//               You shall not download any content from our Website and/or App,
//               unless expressly permitted by Chalo Khelne to do so.
//             </p>
//             <p>
//               You shall solely be responsible for maintaining the necessary
//               computer equipment and/or mobile phone and the necessary hardware
//               and software associated thereto and internet connections that may
//               be required to access and use our Website and/or App.
//             </p>
//             <p>
//               You agree not to access (or attempt to access) the Website and/or
//               App and the materials or Services by any means other than through
//               the interface that is provided by Chalo Khelne. You shall not use
//               any deep-link, robot, spider or other automatic device, program,
//               algorithm or methodology, or any similar or equivalent manual
//               process, to access, acquire, download, copy or monitor any portion
//               of the Website and/or App, or in any way reproduce or circumvent
//               the navigational structure or presentation of the Website and/or
//               App, materials or any content, to obtain or attempt to obtain any
//               materials, documents or information through any means not
//               specifically made available through the Website and/or App.
//             </p>
//             <p>
//               If Website and/or App allows You to post and upload any material
//               on the Website and/or App, You hereby undertake to ensure that
//               such material is not offensive and in accordance with Applicable
//               Laws. Further, You undertake not to:
//             </p>
//             <ul >
//               <li>
//                 {" "}
//                 a) Defame, abuse, harass, threaten or otherwise violate the legal
//                 rights of others;
//               </li>
//               <li>
//                 {" "}
//                 b) Impersonate any person or entity, or falsely state or otherwise
//                 misrepresent Your affiliation with a person or entity;
//               </li>

//               <li>
//                 {" "}
//                 c) Publish, post, submit to upload, distribute or disseminate any
//                 inappropriate, profane, defamatory, infringing, obscene,
//                 indecent or unlawful topic, name, material or information
//                 through any bookmark, tag or keyword;
//               </li>

//               <li>
//                 d) Submit to upload files that contain software or other material
//                 protected by applicable intellectual property laws unless You
//                 own or control the rights thereto or have received all necessary
//                 consents;
//               </li>

//               <li>
//                 {" "}
//                 e) Submit to upload or distribute files that contain viruses,
//                 corrupted files, or any other similar software or programs that
//                 may damage the operation of the Website and/or App or another's
//                 computer;
//               </li>

//               <li>
//                 {" "}
//                 f) Engage in any activity that interferes with or disrupts access
//                 to the Website and/or App or the Services (or the servers and
//                 networks which are connected to the Website and/or App);
//               </li>

//               <li>
//                 {" "}
//                 g) Attempt to indicate in any manner that You have a relationship
//                 with Chalo Khelne or that Chalo Khelne has endorsed You or any
//                 services for any purpose unless Chalo Khelne has provided
//                 written permission to do so;
//               </li>

//               <li>
//                 {" "}
//                 h) Send any unsolicited or unauthorized advertising, solicitations,
//                 promotional materials, spam, junk mail, chain letters or pyramid
//                 schemes, or harvest or collect the email addresses or other
//                 contact information of other users for the purpose of sending
//                 spam or other commercial messages;
//               </li>

//               <li>
//                 {" "}
//                 i) Develop any third-party application that interacts with User
//                 Content or our Services without Chalo Khelne's prior written
//                 consent;
//               </li>

//               <li>
//                 j) Attempt to gain unauthorized access to any portion or feature of
//                 the Website and/or App, any other systems or networks connected
//                 to the Website and/or App, to any Chalo Khelne server, or to any
//                 of the Services offered on or through the Website and/or App, by
//                 hacking, password mining or any other illegitimate means;
//               </li>

//               <li>
//                 {" "}
//                 K) Probe, scan or test the vulnerability of the Website and/or App
//                 or any network connected to the Website and/or App, nor breach
//                 the security or authentication measures on the Website and/or
//                 App or any network connected to the Website and/or App;
//               </li>

//               <li>
//                 {" "}
//                 l) You may not reverse look-up, trace or seek to trace any
//                 information on any other User, of or visitor to, the Website
//                 and/or App, or any other customer of Chalo Khelne, including any
//                 Account not owned by You, to its source, or exploit the Website
//                 and/or App or Service or information made available or offered
//                 by or through the Website and/or App, in any way whether or not
//                 the purpose is to reveal any information, including but not
//                 limited to personal identification information, other than Your
//                 own information, as provided for by the Website and/or App;
//               </li>

//               <li>
//                 m) Disrupt or interfere with the security of, or otherwise cause
//                 harm to, the Website and/or App, systems resources, accounts,
//                 passwords, servers or networks connected to or accessible
//                 through the Website and/or App or any affiliated or linked
//                 sites;
//               </li>

//               <li>
//                 n) Collect or store data about other users in connection with the
//                 prohibited conduct and activities set forth in this Section;
//               </li>

//               <li>
//                 {" "}
//                 o) Use any device or software to interfere or attempt to interfere
//                 with the proper working of the Website and/or App or any
//                 transaction being conducted on the Website and/or App, or with
//                 any other person's use of the Website and/or App;
//               </li>

//               <li>
//                 p) Use the Website and/or App or any material or content for any
//                 purpose that is unlawful or prohibited by these Terms of Use, or
//                 to solicit the performance of any illegal activity or other
//                 activity which infringes the rights of Chalo Khelne or any other
//                 third parties;
//               </li>

//               <li>
//                 {" "}
//                 q) Conduct or forward surveys, contests, pyramid schemes or chain
//                 letters;
//               </li>

//               <li>
//                 {" "}
//                 r) Download any file posted by another User of a Service that You
//                 know, or reasonably should know, cannot be legally distributed
//                 in such manner;
//               </li>

//               <li>
//                s) Falsify or delete any author attributions, legal or other proper
//                 notices or proprietary designations or labels of the origin or
//                 source of software or other material contained in a file that is
//                 submit for uploading or is uploaded;
//               </li>

//               <li>
//                 {" "}
//                T) Violate any code of conduct or other guidelines, which may be
//                 applicable for or to any particular Service;
//               </li>

//               <li>
//                 {" "}
//                U) Violate or breach any Applicable Laws or regulations for the
//                 time being in force within or outside India;
//               </li>

//               <li>
//                 {" "}
//                V) Violate the Terms of Use including but not limited to any
//                 applicable additional terms of the Website and/or App contained
//                 herein or elsewhere;
//               </li>

//               <li>
//                 {" "}
//               W)  Reverse engineer, modify, copy, distribute, transmit, display,
//                 perform, reproduce, publish, license, create derivative works
//                 from, transfer, or sell any information or software obtained
//                 from the Website and/or App;
//               </li>

//               <li>
//                 {" "}
//               X)  Download or copy account information for the benefit of another
//                 User or any other third party; caching, unauthorized hypertext
//                 links to the Website and/or App and the framing of any other
//                 content available through the Website and/or App submitting for
//                 uploading, posting, or transmitting any content that You do not
//                 have a right to make available (such as the intellectual
//                 property of another party);
//               </li>

//               <li>
//                 {" "}
//                Y) any action that imposes or may impose (in our sole discretion)
//                 an unreasonable or disproportionately large load on our
//                 infrastructure; or any use of data mining, robots, or similar
//                 data gathering and extraction tools;
//               </li>

//               <li>
//                 {" "}
//                Z) any unauthorized copying, reproduction, republishing, submit for
//                 uploading, downloading, posting, transmitting or duplicating of
//                 any of the material and/or content is expressly prohibited;
//               </li>

//               <li>
//                 {" "}
//                aa) Post and/or submit for uploading obscene or vulgar materials or
//                 use of obscene or vulgar language, or use of abusive,
//                 defamatory, profane, or threatening language of any kind;
//               </li>

//               <li>
//                 {" "}
//                ab) Undertake any activity which is not in compliance with
//                 applicable Indian and international laws; and
//               </li>
//               <li>
//                 {" "}
//               ac)  Undertake any activity which is not in compliance with
//                 applicable Indian and international laws; and
//               </li>
//               <li>
//                ad) You may not bypass any measures used by us to prevent or
//                 restrict access to the Website and/or App.
//               </li>
//             </ul>
//             <p>
//               {" "}
//            Any unauthorized use by You shall terminate the permission/consent
//               granted to You and Chalo Khelne shall, in its sole discretion,
//               suspend/terminate Your registration and the decision of Chalo
//               Khelne shall be final and binding.
//             </p>
//             <p>
//               {" "}
//             You acknowledge and agree that by accessing or using the Website
//               and/or App or Services, You be exposed to content from other Users
//               that You may consider offensive, indecent or otherwise
//               objectionable. Chalo Khelne disclaims all liabilities arising in
//               relation to such offensive content on the Website and/or App.
//               Further, You may report such offensive content in the manner
//               prescribed under herein. Chalo Khelne shall, in its sole
//               discretion, reserve the right to remove any content uploaded by
//               any User whatsoever reasons. It is hereby clarified that the
//               liability of the material of the any content posted by the User
//               and views expressed therein shall at all times be that of the User
//               contributing such content and Chalo Khelne expressly disclaims all
//               liabilities associated thereto and the User shall be responsible
//               for infringement of any third-party rights.
//             </p>
//             <p>
//               {" "}
//              You agree that Chalo Khelne may, at any time, alter, modify,
//               suspend or discontinue all or part of the Website and/or App,
//               charge, charge fees for use of the Website and/or App, or offer
//               opportunities to some or all Website and/or App Users and for any
//               reason, without notice or cost.
//             </p>
//           </section>
//           <section>
//             <h2>5. App Usage</h2>
//             <p>
//               You agree to use Chalo Khelne only for lawful purposes and in a
//               manner that does not infringe the rights of others or restrict
//               their use and enjoyment of the app. You must not attempt to
//               interfere with the proper working of the app or disrupt its
//               services.
//             </p>
//           </section>

//           <section>
//             <h2>6. User Conduct</h2>
//             <p>You agree not to:</p>
//             <ul>
//               <li>
//                 Upload or share content that is illegal, harmful, or offensive.
//               </li>
//               <li>Impersonate another person or entity.</li>
//               <li>
//                 Use the app for fraudulent activities or to mislead other users.
//               </li>
//             </ul>
//           </section>

//           <section>
//             <h2>7. Intellectual Property</h2>
//             <p>
//               The Website and/or App and the processes, and their selection and
//               arrangement, including but not limited to Software used to access
//               the Services, all text, graphics, User interfaces, visual
//               interfaces, sounds (if any), artwork and computer code on the
//               Website and/or App are protected by rights, including copyright,
//               design rights, database rights and trademarks. All these rights
//               are either owned by us or licensed to us by the rights owner(s)
//               for use with the Services or otherwise used by us as permitted by
//               applicable law and various other national and international IPR
//               laws and regulations.
//             </p>
//             <p>
//               The Services are intended for the individual, personal and
//               non-commercial use by the User only. Accordingly, You may print
//               and download extracts from the Website and/or App for Your own
//               personal, non-commercial use, provided that any material copied
//               remains intact and includes the following notice: Copyright ©
//               2024.Bhalchandraya Innovative Services Private Limited. All Rights
//               Reserved. Any other copying, distribution, storing, framing or
//               transmission of any kind or any sort of commercial use of the
//               material used in the Services or available on Chalo Khelne is
//               strictly prohibited without our express written consent. Unless
//               otherwise indicated or anything contained to the contrary or any
//               proprietary material owned by a third party and so expressly
//               mentioned, Chalo Khelne owns and or has the right to use all IPR
//               to and into the trademark "Chalo Khelne", and the Website and/or
//               App, including, without limitation, compilation of all content,
//               software, any and all rights, title and interest in and to
//               copyright, related rights, patents, utility models, designs,
//               know-how, trade secrets and inventions (patent pending),
//               goodwill,images, audio clips, digital downloads, data
//               compilations, and software, source code, meta tags, databases,
//               text, content, graphics, icons, logos, digital downloads, data
//               compilations, software and the compilation of all contents and
//               hyperlinks.
//             </p>
//             <p>
//               You may not systematically extract/ or re-utilize parts of the
//               contents of Chalo Khelne without the Company's and / or its
//               affiliates (as may be applicable) express written consent. In
//               particular, You may not utilize any data mining, robots, or
//               similar data gathering and extraction tools to extract (whether
//               once or many times) for re-utilization of any substantial parts of
//               Chalo Khelne.
//             </p>
//             <p>
//               Chalo Khelne expressly reserves all IPR in all text, programs,
//               products, processes, technology, content, software and other
//               materials, which appear on this Website and/or App. The
//               compilation (meaning the collection, arrangement and assembly) of
//               the content on the Website and/or App is the exclusive property of
//               Bhalchandraya Innovative Services Private Limited. The mark "Chalo
//               Khelne" and the contents of the Website and/or App are the sole
//               property of Bhalchandraya Innovative Services Private Limited.
//               Reproduction in whole or in part of the same is strictly
//               prohibited without the express written permission of Chalo Khelne.
//               All names, logos, and images on Chalo Khelne constitute trademarks
//               and/or copyrights of Chalo Khelne or the respective content
//               owners. Content shall not be reproduced in any form. Any
//               reproduction or editing by any means mechanical or electronic
//               without the explicit written permission of the respective
//               author/owner of the content and Chalo Khelne is expressly
//               prohibited. You acknowledge and agree that the content, software,
//               materials and other components (including but not limited to our
//               logos, graphics, videos, music, button icons, and page headers)
//               available on the Website and/or App are the property of Chalo
//               Khelne and/or its affiliates, subsidiaries, or licensors and are
//               protected by copyrights, trademarks, service marks, or other
//               proprietary rights and laws. You agree not to sell, license, rent,
//               modify, distribute, copy, reproduce, transmit, publicly display,
//               publicly perform, publish, adapt, edit, cut, copy, modify,
//               recreate, reverse engineer, disseminate, post or create derivative
//               works from, transfer, or sell any information or content or
//               software obtained from Chalo Khelne without our express consent or
//               create derivative works from content or materials on the Website
//               and/or App. Use of the content and materials for any purpose not
//               expressly permitted in these Terms of Use, is prohibited. We are
//               not liable for any infringement of copyrights, trademarks, or
//               other proprietary or IPR arising out of content posted on or
//               transmitted through the Website and/or App, or items advertised on
//               the Website and/or App, by our other users. Further, You agree not
//               to download any material/Content/User Content (including the User
//               Content submitted by You) from the Website and/or App.
//             </p>
//             <p>
//               Except as expressly provided herein, You acknowledge and agree
//               that You shall not copy, republish, post, download, display,
//               translate, transmit, reproduce or distribute any Content through
//               any medium without obtaining the necessary authorization from
//               Chalo Khelne or third party owner of such Content.
//             </p>
//             <p>
//               The User undertakes that any and all content submitted and/or
//               posted by the User, shall be the User's original work and/or the
//               Users shall ensure that they have the legal right to use such work
//               and have the requisite approvals for using and/or permit the
//               uploading such works by us and any such content posted and/or
//               submitted by the to Chalo Khelne, shall be the property of Chalo
//               Khelne and any IPR authorship rights and all other rights of
//               whatsoever nature, in such content, in whatever form or medium,
//               shall vest and remain vested in perpetuity and worldwide with
//               Chalo Khelne and that the User grants Chalo Khelne all existing
//               and future IPR including all copyrights, moral rights, language
//               rights, and any other intellectual rights, of whatsoever nature,
//               in the User Content, worldwide, in perpetuity, without limitation
//               exclusive, royalty-free, transferable without any material,
//               financial or territorial limitation and without any payment and/or
//               consideration due from Chalo Khelne, the right to use, reproduce,
//               distribute, prepare derivative works of, display, publish, adapt,
//               make available online or electronically transmit, and perform the
//               content in connection with Chalo Khelne's services and Chalo
//               Khelne's business, including without limitation for promoting and
//               redistributing part or all of the content (and derivative works
//               thereof) in any media formats and through any media channels,
//               commercially or otherwise. The Users hereby understand that Chalo
//               Khelne does not guarantee any confidentiality with respect to any
//               content that the Users may post or submit for uploading to Chalo
//               Khelne.
//             </p>
//             <p>
//               Notwithstanding anything contained elsewhere in this Terms of Use,
//               it is hereby agreed that the IPR in Chalo Khelne's Confidential
//               Information and the content contributed by Chalo Khelne towards
//               creation of the Website and/or App shall at all times remain the
//               property of Chalo Khelne. Chalo Khelne does not extend any rights
//               of any nature to the User, unless so granted in writing by Chalo
//               Khelne. The User shall not acquire any rights in respect of Chalo
//               Khelne or its group companies names, trademarks, designs, patents,
//               patent applications, copyrights or other IPR, including those
//               obtained from third parties under license or otherwise, for
//               inclusion on its Website and/or App.
//             </p>
//             <p>
//               Intellectual Property or IPR for the purpose of the Terms of Use,
//               shall mean all copyrights (including without limitation the
//               exclusive right to reproduce, distribute copies of, display and
//               perform the copyrighted work and to prepare derivative works),
//               copyright registrations and applications, trademark rights
//               (including, without limitation, registrations and applications),
//               patent rights (whether registered or unregistered), trade names or
//               business names, registered and unregistered design rights,
//               mask-work rights, trade secrets, moral rights, author's rights,
//               rights in packaging, goodwill and other intellectual property
//               rights, and all renewals and extension thereof and all rights or
//               forms of protection of a similar nature or having an equivalent or
//               similar effect to any of the above, which may subsist anywhere in
//               the world, regardless of whether any of such rights arise under
//               the laws of India or any other state, country or jurisdiction.
//             </p>
//           </section>

//           <section>
//             <h2>8. Third-Party Services</h2>
//             <p>
//               The Website and/or App may contain links to other Websites and/or
//               App (Linked Sites). The Linked Sites are not under the control of
//               Chalo Khelne or the Website and/or App and Chalo Khelne is not
//               responsible for the contents of any Linked Site, including without
//               limitation any link contained in a Linked Site, or any changes or
//               updates to a Linked Site. Chalo Khelne is not responsible for any
//               form of transmission, whatsoever, received by You from any Linked
//               Site. Chalo Khelne is providing these links to You only as a
//               convenience, and the inclusion of any link does not imply
//               endorsement by Chalo Khelne or the Website and/or App of the
//               Linked Sites or any association with its operators or owners
//               including the legal heirs or assigns thereof. The Users are
//               requested to verify the accuracy of all information on their own
//               before undertaking any reliance on such information.
//             </p>
//           </section>

//           <section>
//             <h2>9. Limitation of Liability</h2>
//             <p>
//               <ul>
//                 <li>
//                   Chalo Khelne is provided "as is" without any warranties,
//                   express or implied.
//                 </li>
//                 <li>
//                   We are not liable for any direct, indirect, incidental, or
//                   consequential damages arising from your use of the app.
//                 </li>
//               </ul>
//             </p>
//           </section>

//           <section>
//             <h2>10. Indemnification</h2>
//             <p>
//               You agree to indemnify, defend and hold harmless Chalo Khelne from
//               and against any and all losses, liabilities, claims, damages,
//               costs and expenses (including legal fees and disbursements in
//               connection therewith and interest chargeable thereon) asserted
//               against or incurred by Chalo Khelne that arise out of, result
//               from, or may be payable by virtue of, any breach or
//               non-performance of any representation, warranty, covenant or
//               agreement made or obligation to be performed by You pursuant to
//               these Terms of Use.
//             </p>
//             <p>
//               The User shall be solely responsible for its own content and the
//               consequences of submitting for uploading and publishing its
//               content on our Website and/or App. To the extent permitted by
//               applicable law including without limitation the Information
//               Technology Act, 2000, Telecom Commercial Communications Customer
//               Preference Regulations, 2010 and other applicable regulations of
//               TRAI, the User agrees to defend, indemnify and hold harmless Chalo
//               Khelne, its holding, subsidiary, affiliates, officers, directors,
//               employees and agents, from and against any and all claims,
//               damages, obligations, losses, liabilities, costs or debt, and
//               expenses (including but not limited to attorney's fees) arising
//               from: (i) the User's use of and access to the Service; (ii) the
//               User's violation of any term of these Terms of Use; (iii) the
//               User's violation of any third party right, including without
//               limitation any copyright, property, or privacy right; or (iv) any
//               claim that the content posted by the User caused damage to a third
//               party or (v) or arising out of non-compliance with any applicable
//               law and rules or regulations by the User or arising from any suit,
//               action or proceeding by any third party against any of the
//               indemnified persons, as a result of or in consequence of any act
//               or omission of whatsoever nature of the User, including without
//               prejudice to the generality of the foregoing, any complaint or
//               loss or damage or claim for compensation arising out of the
//               infringement of third party IPR.
//             </p>
//           </section>

//           <section>
//             <h2>11. Changes to Terms</h2>
//             <p>
//               We may update these Terms and Conditions from time to time. We
//               will notify users of any significant changes. Continued use of the
//               app after such updates constitutes your acceptance of the revised
//               terms.
//             </p>
//           </section>

//           <section>
//             <h2>12. Compliance with laws</h2>
//             <p>
//               You shall be solely responsible for compliance of all statutes,
//               enactments, acts of legislature or parliament, ordinances, rules,
//               bye-laws, regulations, notifications, guidelines, policies,
//               directions, directives and orders of any Governmental Authority,
//               statutory authority, tribunal, board or court in India or outside
//               India (Applicable Laws) for:
//             </p>
//             <ul>
//               <li>Use of the Website and/or App;</li>
//               <li>Use of Services available on the Website and/or App;</li>
//               <li>
//                 Posting and/or uploading any content on the Website and/or App.
//               </li>
//             </ul>
//           </section>
//           <section>
//           <h2>13. Contact US</h2>
//             <p>
//               If you have any questions about these Terms and Conditions, please
//               contact us at:
//             </p>
//             <p>
//               <b>Email:</b>sales@chalokhelne.com
//             </p>
//             <p><b>Phone:</b>+91 9272090926
//             </p>
//           </section>
//         </div>
//       </div>

//     </>
//   );
// }

// export default LTerms_Conditions;
import React from "react";
import { useNavigate } from "react-router-dom";
import PrivacyImage from '../assets/PrivacyPolicy.jpg'; // adjust the path if necessary

function LTerms_Conditions() {
  const navigate = useNavigate();

  const handleBackToHome = () => {
    navigate("/");
  };

  return (
    <div className="w-full">
      {/* Header Section */}
      <div className="relative w-full h-72">
        <div
          className="absolute inset-0 bg-cover bg-center"
          style={{ backgroundImage: `url(${PrivacyImage})` }}
        >
          <div className="absolute inset-0 bg-black bg-opacity-50 flex flex-col justify-center items-center text-center p-4">
            <h1 className="text-3xl md:text-4xl font-bold text-white mb-6">Terms and Condition</h1>
            <button
              onClick={handleBackToHome}
              className="px-6 py-3 bg-gradient-to-r from-orange-600 to-orange-500 text-white font-semibold rounded-lg hover:from-orange-700 hover:to-orange-600 transition duration-300 w-auto"
            >
              Back to Home Page
            </button>
          </div>
        </div>
      </div>

      {/* Content Container */}
      <div className="w-full flex justify-center">
        <div className="w-11/12 md:w-4/5 max-w-6xl my-8 p-4 md:p-6 bg-gray-50 rounded-lg shadow-md">
          <p className="text-gray-700 mb-4">Effective Date: 06-12-2024</p>
          <p className="text-gray-700 mb-4">
            You have accessed our app (App) and/or our Website
            www.chalokhelne.com (Website). The domain name Chalo Khelne is owned
            by Bhalchandraya Innovative Services Private Limited, a private
            company incorporated under the (Indian) Companies Act, 2013 bearing
            CIN U72900PN2022PTC211674 and its registration number is 211674. The
            Website and/or App are internet-based portals developed by Baranwal
            Consultancy and Services.
          </p>
          <p className="text-gray-700 mb-4">
            These Terms and Conditions of use (Terms of Use) are between Chalo
            Khelne and the users who visit us and/or are registered with us, by
            following our registration process and the users that use our
            Services as defined hereinafter or any part thereof on and from our
            Website and/or App (You or Your or Users). It is hereby clarified
            that the term User shall deem to include all users of the Website,
            including without limitation users who are browsing, individuals or
            the family members of the individuals who obtain and/or intend to
            obtain our services, coaches, academies, service providers,
            merchants, and/or are in any manner connected with and/or contribute
            to the use of the Website and/or App and/or the Services provided
            through it.
          </p>
          <p className="text-gray-700 mb-4">
            Please read these Terms of Use carefully before using or registering
            or accessing any information or Services through the Website and/or
            App. By using the Website and/or App or any facility or Services
            provided by the Website and/or App in any manner whatsoever or by
            merely browsing the Website and/or App, You signify Your acceptance
            and shall be legally bound by these Terms of Use, along with any
            amendments made by Chalo Khelne, at its sole discretion and posted
            and/or updated on the Website and/or App, and the applicable
            policies which are incorporated herein by way of reference and as
            amended from time to time. If these Terms of Use conflict with any
            other document, these Terms of Use will prevail for the purposes of
            usage of the Website and/or App. If You do not agree to all or any
            of the Terms of Use, we recommend You to cease Your access to the
            Website and/or App or use any Services.
          </p>
          <p className="text-gray-700 mb-4">
            These Terms of Use are published in accordance with the provisions
            of Rule 3 (1) of the Information Technology (Intermediaries
            guidelines) Rules, 2011 that require publishing the privacy policy
            and terms of use for access or usage of the Website and/or App and
            is an electronic record in terms of Information Technology Act, 2000
            and rules thereunder, as applicable, and the amended provisions
            pertaining to electronic records in various statutes as amended by
            the Information Technology Act, 2000. This electronic record is
            generated by a computer system and does not require any physical or
            digital signatures.
          </p>
          <div className="mb-8">
            <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">AMENDMENT</h2>
            <p className="text-gray-700 mb-4">
              Chalo Khelne reserves the right, at its sole discretion, to change,
              modify, add or remove portions of these Terms of Use, at any time
              without any prior written notice to You. The revised Terms of Use
              shall be made available on the Website and/or App. Your use of the
              Website and/or App and the Services is subject to the most current
              version of the Terms of Use made available on the Website and/or App
              at the time of such use. It is Your responsibility to review these
              Terms of Use periodically for updates/changes. Your continued use of
              the Website and/or App following the posting of changes will mean
              that You accept and agree to the revisions. Any new features or
              tools which are added to the Website and/or App shall also be
              subject to the Terms of Use.
            </p>
            <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">Eligibility To Use</h2>
            <p className="text-gray-700 mb-4">
              Use of the Website and/or App is available only to persons who can
              form legally binding contracts under Indian Contract Act, 1872.
              Persons who are incompetent to contract within the meaning of the
              Indian Contract Act, 1872 including minors, un-discharged insolvents
              etc. are not eligible to use the Website and/or App. As a minor if
              You wish to use the Website and/or App, such use may be made through
              Your legal guardian or parents who will be deemed to have given
              their consent to allow any of their minor dependents to use this
              Website and/or App at the risks and consequences of the legal
              guardian or parents, as the case may be.
            </p>
            <p className="text-gray-700 mb-4">
              Chalo Khelne reserves the right to terminate Your registration
              and/or refuse to provide You with access to the Website and/or App
              if it is brought to Chalo Khelne's notice or if it is discovered or
              if Chalo Khelne has reason to believe that You are incompetent to
              contract within the meaning of the Indian Contract Act, 1872.
              Further, Chalo Khelne reserves the right to refuse access to use the
              Services offered at the Website and/or App to new Users or to
              suspend and/or terminate access granted to existing and/or
              registered Users at any time without according any reasons for doing
              so.
            </p>
          </div>

          <div className="mb-8">
            <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">ELIGIBILITY TO USE</h2>
            <p className="text-gray-700 mb-4">
              Use of the Website and/or App is available only to persons who can
              form legally binding contracts under Indian Contract Act, 1872.
              Persons who are incompetent to contract within the meaning of the
              Indian Contract Act, 1872 including minors, un-discharged insolvents
              etc. are not eligible to use the Website and/or App. As a minor if
              You wish to use the Website and/or App, such use may be made through
              Your legal guardian or parents who will be deemed to have given
              their consent to allow any of their minor dependents to use this
              Website and/or App at the risks and consequences of the legal
              guardian or parents, as the case may be.
            </p>
            <p className="text-gray-700 mb-4">
              Chalo Khelne reserves the right to terminate Your registration
              and/or refuse to provide You with access to the Website and/or App
              if it is brought to Chalo Khelne's notice or if it is discovered or
              if Chalo Khelne has reason to believe that You are incompetent to
              contract within the meaning of the Indian Contract Act, 1872.
              Further, Chalo Khelne reserves the right to refuse access to use the
              Services offered at the Website and/or App to new Users or to
              suspend and/or terminate access granted to existing and/or
              registered Users at any time without according any reasons for doing
              so.
            </p>
          </div>

          {/* Section 1: Acceptance of Terms */}
          <div className="mb-8">
            <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">1. Acceptance of Terms</h2>
            <p className="text-gray-700 mb-4">
              By using Chalo Khelne, you acknowledge that you have read,
              understood, and agree to be bound by these Terms and Conditions.
            </p>
          </div>

          {/* Section 2: User Account */}
          <div className="mb-8">
            <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">2. User Account</h2>
            <p className="text-gray-700 mb-4">
              You shall have to apply for registration as a User to use our
              Website and/or App. Chalo Khelne shall provide the Services to You
              through the Website and/or App only, if You have created an
              account and are registered with us.
              <br /><br />
              We shall be entitled to ask You to submit certain information
              (Account Information) that shall qualify the eligibility criterias
              laid down for registration by Chalo Khelne from time to time. Each
              registered User will be given a unique registration id/Your name
              and password. You can even apply for registration through any
              other login ID and password (including Facebook, Gmail or Yahoo
              ID) (Account). Chalo Khelne reserves the right to ask the
              applicant for more information, if necessary. Chalo Khelne may,
              for reasons it deems necessary, refuse registration of any User
              and it is clarified that the decision of Chalo Khelne, in this
              case, shall be final and conclusive. You shall ensure that the
              Account Information provided by You is complete, true and
              accurate. If You provide any information that is untrue,
              inaccurate, not current or incomplete (or becomes untrue,
              inaccurate, not current or incomplete), or Chalo Khelne has
              reasonable grounds to suspect that such information is untrue,
              inaccurate, not current or incomplete, Chalo Khelne has the right
              to suspend and/or terminate Your Account and refuse any and all
              current or future use of the Website and/or App (or any portion
              thereof). However, Chalo Khelne reserves the right to allow
              restricted access to the Services for unregistered users but in
              such a case, only few functionalities of the Website and/or App
              and/or Services may be available for Your use. You shall be
              responsible for maintaining the confidentiality of the Account
              Information and restricting access to Your
              computer/phone/tablet/any other device to prevent unauthorised
              access to Your Account. You shall be fully responsible for all
              activities that occur through Your Account. You shall:
            </p>
            <ul className="list-disc pl-5 mb-4 space-y-2">
              <li className="text-gray-700">
                register in Your own name only and all Account Information
                provided by You will be accurate and up-to-date;
              </li>
              <li className="text-gray-700">
                not pass yourself off as someone else or create multiple and/or false
                Accounts;
              </li>
              <li className="text-gray-700">
                promptly update any of Your Account Information in
                case of any change in the same and also update any new Account
                Information as required by Chalo Khelne to do so;
              </li>
              <li className="text-gray-700">
                not transfer
                Your membership/registration to another person;
              </li>
              <li className="text-gray-700">
                immediately
                notify Chalo Khelne of any unauthorized use of Your Account or any
                breach of security;
              </li>
              <li className="text-gray-700">
                inform Chalo Khelne immediately if You have
                reason to believe that Your password is known to someone else or
                if Your Account is being, or is likely to be, used in an
                unauthorized manner;
              </li>
              <li className="text-gray-700">
                log out of Your Account at the end of each
                session.
              </li>
              {/* Other list items */}
            </ul>
            <p className="text-gray-700 mb-4">
              Chalo Khelne shall not be responsible for Your failure to comply
              with the above. You may be held liable for any loss incurred by
              Chalo Khelne or any other third party due to any authorized or
              unauthorized use of Your Account and You shall be responsible to
              indemnify Chalo Khelne for the same.
            </p>
            <p className="text-gray-700 mb-4">
              You can access and administer Your Account by entering the
              username and password. You can also update Your personal details
              (including Your Account Information and preferences) by accessing
              Your Account and making any necessary changes; this will update
              Your details across all Services of Chalo Khelne. Chalo Khelne
              would use this information to provide Your recommendations and
              options related to the Services requested by You. To deactivate
              Your account, You may follow the instructions given on our Website
              and/or App or You may contact our customer support team.
              Incomplete cancellation requests will be deemed invalid and will
              not be processed. You will be responsible for any payments that
              arise from Your failure to deactivate Your account.
            </p>
          </div>

          {/* Section 3: Termination/Suspension */}
          <div className="mb-8">
            <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">3. Termination/ Suspension of Account</h2>
            <p className="text-gray-700 mb-4">
              We reserve the right to terminate or suspend Your Account and/or
              suspend Your access to the Services under the following
              circumstances:
            </p>
            <ul className="list-disc pl-5 mb-4 space-y-2">
              <li className="text-gray-700">
                You are in breach of any term or condition of this Terms of Use;
              </li>
              <li className="text-gray-700">
                You are in breach of any laws that are applicable to You;
              </li>
              <li className="text-gray-700">
                Your use of the Service disrupts our business operations;              </li>
              <li className="text-gray-700">
                You have behaved in a way that is unlawful or brings us into
                disrepute. </li>
              {/* Other list items */}
            </ul>
            <p className="text-gray-700 mb-4">
              We may suspend access to the Services or require You to change
              Your password if we reasonably believe that the Services have been
              or are likely to be misused, and we will notify You accordingly.
              Chalo Khelne may constantly monitor the User's Account in order to
              avoid fraudulent accounts. Users with more than one account or
              availing our Services fraudulently shall be liable for legal
              actions under applicable law. We reserve the right to initiate
              legal proceedings against such persons for fraudulent use of the
              Website and/or App and any other unlawful acts or omissions in
              breach of these Terms of Use. In the event of detection of any
              fraudulent action, prior to initiation of legal actions, we
              reserve the right to immediately delete such Account. Any
              termination of Your registration and/or Account or the Services
              will not affect liability previously incurred by You.
            </p>

            <p className="text-gray-700 mb-4">
              If at any time, we notify You that Your access to and/or use of
              the Website and/or App or Your Account is suspended and/or
              terminated, You must cease and desist from all such access and/or
              use immediately.
            </p>

          </div>

          {/* Continue with other sections following the same pattern */}
          <div className="mb-8">
            <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">User Obligations</h2>
            <p className="text-gray-700 mb-4">
              You agree to use the Services, Website and/or App and the content
              provided therein only for purposes that are permitted by: (a) the
              Terms of Use; and (b) any applicable law, regulation or generally
              accepted practices or guidelines in India and under any applicable
              law of other jurisdictions.
            </p>
            <p className="text-gray-700 mb-4">
              You agree to adhere to all limitations on dissemination, use and
              reproduction of any materials that You access on the Website
              and/or App. We grant You a limited license to access and make use
              of our Website and/or App, however the following usages are not
              permitted:
            </p>
            <ul className="list-disc pl-5 mb-4 space-y-2">
              <li className="text-gray-700">
                downloading (other than page caching) or modifying content or
                any portion of it, on our App and/or Website, except with our
                express written consent;
              </li>
              <li className="text-gray-700">
                any resale or commercial use, except as provided hereunder
                and agreed between Chalo Khelne and You;              </li>
              <li className="text-gray-700">
                downloading or using other User's content without Chalo
                Khelne's prior written consent;  </li>
              <li className="text-gray-700">
                any collection and use of any content, descriptions; any
                derivative use of Website and/or App or its contents; </li>
              <li className="text-gray-700">
                any downloading or copying of Account information for the
                benefit of another person. </li>
              {/* Other list items */}
            </ul>
            <p className="text-gray-700 mb-4">
              You shall not download any content from our Website and/or App,
              unless expressly permitted by Chalo Khelne to do so.
            </p>
            <p className="text-gray-700 mb-4">
              You shall solely be responsible for maintaining the necessary
              computer equipment and/or mobile phone and the necessary hardware
              and software associated thereto and internet connections that may
              be required to access and use our Website and/or App.
            </p>
            <p className="text-gray-700 mb-4">
              You agree not to access (or attempt to access) the Website and/or
              App and the materials or Services by any means other than through
              the interface that is provided by Chalo Khelne. You shall not use
              any deep-link, robot, spider or other automatic device, program,
              algorithm or methodology, or any similar or equivalent manual
              process, to access, acquire, download, copy or monitor any portion
              of the Website and/or App, or in any way reproduce or circumvent
              the navigational structure or presentation of the Website and/or
              App, materials or any content, to obtain or attempt to obtain any
              materials, documents or information through any means not
              specifically made available through the Website and/or App.
            </p>
            <p className="text-gray-700 mb-4">
              If Website and/or App allows You to post and upload any material
              on the Website and/or App, You hereby undertake to ensure that
              such material is not offensive and in accordance with Applicable
              Laws. Further, You undertake not to:
            </p>
            <ul className="list-disc pl-5 mb-4 space-y-2">
              <li className="text-gray-700">
                Defame, abuse, harass, threaten or otherwise violate the legal
                rights of others;
              </li>
              <li className="text-gray-700">
                Impersonate any person or entity, or falsely state or otherwise
                misrepresent Your affiliation with a person or entity;            </li>
              <li className="text-gray-700">
                Publish, post, submit to upload, distribute or disseminate any
                inappropriate, profane, defamatory, infringing, obscene,
                indecent or unlawful topic, name, material or information
                through any bookmark, tag or keyword;  </li>
              <li className="text-gray-700">
                Submit to upload files that contain software or other material
                protected by applicable intellectual property laws unless You
                own or control the rights thereto or have received all necessary
                consents; </li>
              <li className="text-gray-700">
                Engage in any activity that interferes with or disrupts access
                to the Website and/or App or the Services (or the servers and
                networks which are connected to the Website and/or App);</li>
              <li className="text-gray-700">
                Attempt to indicate in any manner that You have a relationship
                with Chalo Khelne or that Chalo Khelne has endorsed You or any
                services for any purpose unless Chalo Khelne has provided
                written permission to do so;</li>
              <li className="text-gray-700">
                Submit to upload or distribute files that contain viruses,
                corrupted files, or any other similar software or programs that
                may damage the operation of the Website and/or App or another's
                computer; </li>
              <li className="text-gray-700">
                Send any unsolicited or unauthorized advertising, solicitations,
                promotional materials, spam, junk mail, chain letters or pyramid
                schemes, or harvest or collect the email addresses or other
                contact information of other users for the purpose of sending
                spam or other commercial messages;</li>
              <li className="text-gray-700">
                Develop any third-party application that interacts with User
                Content or our Services without Chalo Khelne's prior written
                consent; </li>
              <li className="text-gray-700">
                Attempt to gain unauthorized access to any portion or feature of
                the Website and/or App, any other systems or networks connected
                to the Website and/or App, to any Chalo Khelne server, or to any
                of the Services offered on or through the Website and/or App, by
                hacking, password mining or any other illegitimate means; </li>
              <li className="text-gray-700">
                Probe, scan or test the vulnerability of the Website and/or App
                or any network connected to the Website and/or App, nor breach
                the security or authentication measures on the Website and/or
                App or any network connected to the Website and/or App;</li>
              <li className="text-gray-700">
                You may not reverse look-up, trace or seek to trace any
                information on any other User, of or visitor to, the Website
                and/or App, or any other customer of Chalo Khelne, including any
                Account not owned by You, to its source, or exploit the Website
                and/or App or Service or information made available or offered
                by or through the Website and/or App, in any way whether or not
                the purpose is to reveal any information, including but not
                limited to personal identification information, other than Your
                own information, as provided for by the Website and/or App;</li>
              <li className="text-gray-700">
                Disrupt or interfere with the security of, or otherwise cause
                harm to, the Website and/or App, systems resources, accounts,
                passwords, servers or networks connected to or accessible
                through the Website and/or App or any affiliated or linked
                sites;</li>
              <li className="text-gray-700">
                Collect or store data about other users in connection with the
                prohibited conduct and activities set forth in this Section;</li>
              <li className="text-gray-700">
                Conduct or forward surveys, contests, pyramid schemes or chain
                letters;</li>
              <li className="text-gray-700">
                Download any file posted by another User of a Service that You
                know, or reasonably should know, cannot be legally distributed
                in such manner;</li>
              <li className="text-gray-700">
                Falsify or delete any author attributions, legal or other proper
                notices or proprietary designations or labels of the origin or
                source of software or other material contained in a file that is
                submit for uploading or is uploaded;</li>
              <li className="text-gray-700">
                Violate any code of conduct or other guidelines, which may be
                applicable for or to any particular Service;</li>
              <li className="text-gray-700">
                Violate or breach any Applicable Laws or regulations for the
                time being in force within or outside India;</li>
              <li className="text-gray-700">
                Violate the Terms of Use including but not limited to any
                applicable additional terms of the Website and/or App contained
                herein or elsewhere;</li>
              <li className="text-gray-700">
                Download or copy account information for the benefit of another
                User or any other third party; caching, unauthorized hypertext
                links to the Website and/or App and the framing of any other
                content available through the Website and/or App submitting for
                uploading, posting, or transmitting any content that You do not
                have a right to make available (such as the intellectual
                property of another party);</li>
              <li className="text-gray-700">
                any action that imposes or may impose (in our sole discretion)
                an unreasonable or disproportionately large load on our
                infrastructure; or any use of data mining, robots, or similar
                data gathering and extraction tools;</li>
              <li className="text-gray-700">
                any unauthorized copying, reproduction, republishing, submit for
                uploading, downloading, posting, transmitting or duplicating of
                any of the material and/or content is expressly prohibited;</li>
              <li className="text-gray-700">
                Post and/or submit for uploading obscene or vulgar materials or
                use of obscene or vulgar language, or use of abusive,
                defamatory, profane, or threatening language of any kind;</li>
              <li className="text-gray-700">
                Undertake any activity which is not in compliance with
                applicable Indian and international laws; You may not bypass any measures used by us to prevent or
                restrict access to the Website and/or App.</li>

              {/* Other list items */}
            </ul>
            <p className="text-gray-700 mb-4">
              {" "}
              Any unauthorized use by You shall terminate the permission/consent
              granted to You and Chalo Khelne shall, in its sole discretion,
              suspend/terminate Your registration and the decision of Chalo
              Khelne shall be final and binding.
            </p>
            <p className="text-gray-700 mb-4">
              {" "}
              You acknowledge and agree that by accessing or using the Website
              and/or App or Services, You be exposed to content from other Users
              that You may consider offensive, indecent or otherwise
              objectionable. Chalo Khelne disclaims all liabilities arising in
              relation to such offensive content on the Website and/or App.
              Further, You may report such offensive content in the manner
              prescribed under herein. Chalo Khelne shall, in its sole
              discretion, reserve the right to remove any content uploaded by
              any User whatsoever reasons. It is hereby clarified that the
              liability of the material of the any content posted by the User
              and views expressed therein shall at all times be that of the User
              contributing such content and Chalo Khelne expressly disclaims all
              liabilities associated thereto and the User shall be responsible
              for infringement of any third-party rights.
            </p>
            <p className="text-gray-700 mb-4">
              {" "}
              You agree that Chalo Khelne may, at any time, alter, modify,
              suspend or discontinue all or part of the Website and/or App,
              charge, charge fees for use of the Website and/or App, or offer
              opportunities to some or all Website and/or App Users and for any
              reason, without notice or cost.
            </p>
          </div>
          <div className="mb-8">
            <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">5. App Usage</h2>
            <p className="text-gray-700 mb-4">
              You agree to use Chalo Khelne only for lawful purposes and in a
              manner that does not infringe the rights of others or restrict
              their use and enjoyment of the app. You must not attempt to
              interfere with the proper working of the app or disrupt its
              services.
            </p>
          </div>
          <div className="mb-8">
            <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">6. User Conduct</h2>
            <ul className="list-disc pl-5 mb-4 space-y-2">
              <li className="text-gray-700">
                Upload or share content that is illegal, harmful, or offensive.

              </li>
              <li className="text-gray-700">
                Impersonate another person or entity.
              </li>
              <li className="text-gray-700">
                Use the app for fraudulent activities or to mislead other users.

              </li>

              {/* Other list items */}
            </ul>

          </div>
          <div className="mb-8">
            <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">7. Intellectual Property</h2>
            <p className="text-gray-700 mb-4">  The Website and/or App and the processes, and their selection and
              arrangement, including but not limited to Software used to access
              the Services, all text, graphics, User interfaces, visual
              interfaces, sounds (if any), artwork and computer code on the
              Website and/or App are protected by rights, including copyright,
              design rights, database rights and trademarks. All these rights
              are either owned by us or licensed to us by the rights owner(s)
              for use with the Services or otherwise used by us as permitted by
              applicable law and various other national and international IPR
              laws and regulations.</p>
            <p className="text-gray-700 mb-4">  The Services are intended for the individual, personal and
              non-commercial use by the User only. Accordingly, You may print
              and download extracts from the Website and/or App for Your own
              personal, non-commercial use, provided that any material copied
              remains intact and includes the following notice: Copyright ©
              2024.Bhalchandraya Innovative Services Private Limited. All Rights
              Reserved. Any other copying, distribution, storing, framing or
              transmission of any kind or any sort of commercial use of the
              material used in the Services or available on Chalo Khelne is
              strictly prohibited without our express written consent. Unless
              otherwise indicated or anything contained to the contrary or any
              proprietary material owned by a third party and so expressly
              mentioned, Chalo Khelne owns and or has the right to use all IPR
              to and into the trademark "Chalo Khelne", and the Website and/or
              App, including, without limitation, compilation of all content,
              software, any and all rights, title and interest in and to
              copyright, related rights, patents, utility models, designs,
              know-how, trade secrets and inventions (patent pending),
              goodwill,images, audio clips, digital downloads, data
              compilations, and software, source code, meta tags, databases,
              text, content, graphics, icons, logos, digital downloads, data
              compilations, software and the compilation of all contents and
              hyperlinks.</p>
            <p className="text-gray-700 mb-4">  You may not systematically extract/ or re-utilize parts of the
              contents of Chalo Khelne without the Company's and / or its
              affiliates (as may be applicable) express written consent. In
              particular, You may not utilize any data mining, robots, or
              similar data gathering and extraction tools to extract (whether
              once or many times) for re-utilization of any substantial parts of
              Chalo Khelne.</p>
            <p className="text-gray-700 mb-4"> Chalo Khelne expressly reserves all IPR in all text, programs,
              products, processes, technology, content, software and other
              materials, which appear on this Website and/or App. The
              compilation (meaning the collection, arrangement and assembly) of
              the content on the Website and/or App is the exclusive property of
              Bhalchandraya Innovative Services Private Limited. The mark "Chalo
              Khelne" and the contents of the Website and/or App are the sole
              property of Bhalchandraya Innovative Services Private Limited.
              Reproduction in whole or in part of the same is strictly
              prohibited without the express written permission of Chalo Khelne.
              All names, logos, and images on Chalo Khelne constitute trademarks
              and/or copyrights of Chalo Khelne or the respective content
              owners. Content shall not be reproduced in any form. Any
              reproduction or editing by any means mechanical or electronic
              without the explicit written permission of the respective
              author/owner of the content and Chalo Khelne is expressly
              prohibited. You acknowledge and agree that the content, software,
              materials and other components (including but not limited to our
              logos, graphics, videos, music, button icons, and page headers)
              available on the Website and/or App are the property of Chalo
              Khelne and/or its affiliates, subsidiaries, or licensors and are
              protected by copyrights, trademarks, service marks, or other
              proprietary rights and laws. You agree not to sell, license, rent,
              modify, distribute, copy, reproduce, transmit, publicly display,
              publicly perform, publish, adapt, edit, cut, copy, modify,
              recreate, reverse engineer, disseminate, post or create derivative
              works from, transfer, or sell any information or content or
              software obtained from Chalo Khelne without our express consent or
              create derivative works from content or materials on the Website
              and/or App. Use of the content and materials for any purpose not
              expressly permitted in these Terms of Use, is prohibited. We are
              not liable for any infringement of copyrights, trademarks, or
              other proprietary or IPR arising out of content posted on or
              transmitted through the Website and/or App, or items advertised on
              the Website and/or App, by our other users. Further, You agree not
              to download any material/Content/User Content (including the User
              Content submitted by You) from the Website and/or App.</p>
            <p className="text-gray-700 mb-4">    Except as expressly provided herein, You acknowledge and agree
              that You shall not copy, republish, post, download, display,
              translate, transmit, reproduce or distribute any Content through
              any medium without obtaining the necessary authorization from
              Chalo Khelne or third party owner of such Content.</p>
            <p className="text-gray-700 mb-4"> The User undertakes that any and all content submitted and/or
              posted by the User, shall be the User's original work and/or the
              Users shall ensure that they have the legal right to use such work
              and have the requisite approvals for using and/or permit the
              uploading such works by us and any such content posted and/or
              submitted by the to Chalo Khelne, shall be the property of Chalo
              Khelne and any IPR authorship rights and all other rights of
              whatsoever nature, in such content, in whatever form or medium,
              shall vest and remain vested in perpetuity and worldwide with
              Chalo Khelne and that the User grants Chalo Khelne all existing
              and future IPR including all copyrights, moral rights, language
              rights, and any other intellectual rights, of whatsoever nature,
              in the User Content, worldwide, in perpetuity, without limitation
              exclusive, royalty-free, transferable without any material,
              financial or territorial limitation and without any payment and/or
              consideration due from Chalo Khelne, the right to use, reproduce,
              distribute, prepare derivative works of, display, publish, adapt,
              make available online or electronically transmit, and perform the
              content in connection with Chalo Khelne's services and Chalo
              Khelne's business, including without limitation for promoting and
              redistributing part or all of the content (and derivative works
              thereof) in any media formats and through any media channels,
              commercially or otherwise. The Users hereby understand that Chalo
              Khelne does not guarantee any confidentiality with respect to any
              content that the Users may post or submit for uploading to Chalo
              Khelne.</p>
            <p className="text-gray-700 mb-4">  Notwithstanding anything contained elsewhere in this Terms of Use,
              it is hereby agreed that the IPR in Chalo Khelne's Confidential
              Information and the content contributed by Chalo Khelne towards
              creation of the Website and/or App shall at all times remain the
              property of Chalo Khelne. Chalo Khelne does not extend any rights
              of any nature to the User, unless so granted in writing by Chalo
              Khelne. The User shall not acquire any rights in respect of Chalo
              Khelne or its group companies names, trademarks, designs, patents,
              patent applications, copyrights or other IPR, including those
              obtained from third parties under license or otherwise, for
              inclusion on its Website and/or App.</p>
            <p className="text-gray-700 mb-4"> Intellectual Property or IPR for the purpose of the Terms of Use,
              shall mean all copyrights (including without limitation the
              exclusive right to reproduce, distribute copies of, display and
              perform the copyrighted work and to prepare derivative works),
              copyright registrations and applications, trademark rights
              (including, without limitation, registrations and applications),
              patent rights (whether registered or unregistered), trade names or
              business names, registered and unregistered design rights,
              mask-work rights, trade secrets, moral rights, author's rights,
              rights in packaging, goodwill and other intellectual property
              rights, and all renewals and extension thereof and all rights or
              forms of protection of a similar nature or having an equivalent or
              similar effect to any of the above, which may subsist anywhere in
              the world, regardless of whether any of such rights arise under
              the laws of India or any other state, country or jurisdiction.</p>

          </div>
          <div className="mb-8">
            <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">8. Third-Party Services</h2>
            <p className="text-gray-700 mb-4">
              The Website and/or App may contain links to other Websites and/or
              App (Linked Sites). The Linked Sites are not under the control of
              Chalo Khelne or the Website and/or App and Chalo Khelne is not
              responsible for the contents of any Linked Site, including without
              limitation any link contained in a Linked Site, or any changes or
              updates to a Linked Site. Chalo Khelne is not responsible for any
              form of transmission, whatsoever, received by You from any Linked
              Site. Chalo Khelne is providing these links to You only as a
              convenience, and the inclusion of any link does not imply
              endorsement by Chalo Khelne or the Website and/or App of the
              Linked Sites or any association with its operators or owners
              including the legal heirs or assigns thereof. The Users are
              requested to verify the accuracy of all information on their own
              before undertaking any reliance on such information.
            </p>

          </div>
          <div className="mb-8">
            <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">9. Limitation of Liability</h2>
            <ul className="list-disc pl-5 mb-4 space-y-2">
              <li className="text-gray-700">
                Chalo Khelne is provided "as is" without any warranties,
                express or implied.
              </li>
              <li className="text-gray-700">
                We are not liable for any direct, indirect, incidental, or
                consequential damages arising from your use of the app.
              </li>
            </ul>
          </div>
          <div className="mb-8">
            <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">10. Indemnification</h2>
            <p className="text-gray-700 mb-4">
              You agree to indemnify, defend and hold harmless Chalo Khelne from
              and against any and all losses, liabilities, claims, damages,
              costs and expenses (including legal fees and disbursements in
              connection therewith and interest chargeable thereon) asserted
              against or incurred by Chalo Khelne that arise out of, result
              from, or may be payable by virtue of, any breach or
              non-performance of any representation, warranty, covenant or
              agreement made or obligation to be performed by You pursuant to
              these Terms of Use.
            </p>
            <p className="text-gray-700">
              The User shall be solely responsible for its own content and the
              consequences of submitting for uploading and publishing its
              content on our Website and/or App. To the extent permitted by
              applicable law including without limitation the Information
              Technology Act, 2000, Telecom Commercial Communications Customer
              Preference Regulations, 2010 and other applicable regulations of
              TRAI, the User agrees to defend, indemnify and hold harmless Chalo
              Khelne, its holding, subsidiary, affiliates, officers, directors,
              employees and agents, from and against any and all claims,
              damages, obligations, losses, liabilities, costs or debt, and
              expenses (including but not limited to attorney's fees) arising
              from: (i) the User's use of and access to the Service; (ii) the
              User's violation of any term of these Terms of Use; (iii) the
              User's violation of any third party right, including without
              limitation any copyright, property, or privacy right; or (iv) any
              claim that the content posted by the User caused damage to a third
              party or (v) or arising out of non-compliance with any applicable
              law and rules or regulations by the User or arising from any suit,
              action or proceeding by any third party against any of the
              indemnified persons, as a result of or in consequence of any act
              or omission of whatsoever nature of the User, including without
              prejudice to the generality of the foregoing, any complaint or
              loss or damage or claim for compensation arising out of the
              infringement of third party IPR.
            </p>

          </div>
          <div className="mb-8">
            <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">11. Changes to Terms</h2>
            <p className="text-gray-700 mb-4">
              We may update these Terms and Conditions from time to time. We
              will notify users of any significant changes. Continued use of the
              app after such updates constitutes your acceptance of the revised
              terms.
            </p>

          </div>
          <div className="mb-8">
            <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">12. Compliance with laws</h2>
            <p className="text-gray-700 mb-4">
              You shall be solely responsible for compliance of all statutes,
              enactments, acts of legislature or parliament, ordinances, rules,
              bye-laws, regulations, notifications, guidelines, policies,
              directions, directives and orders of any Governmental Authority,
              statutory authority, tribunal, board or court in India or outside
              India (Applicable Laws) for:
            </p>
            <ul className="list-disc pl-5 mb-4 space-y-2">
              <li className="text-gray-700">Use of the Website and/or App;</li>
              <li className="text-gray-700">Use of Services available on the Website and/or App;</li>
              <li className="text-gray-700">
                Posting and/or uploading any content on the Website and/or App.
              </li>
            </ul>
          </div>
          {/* Section 13: Contact US */}
          <div className="mb-8">
            <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">13. Contact US</h2>
            <p className="text-gray-700 mb-4">
              If you have any questions about these Terms and Conditions, please
              contact us at:
            </p>
            <p className="text-gray-700">
              <span className="font-semibold">Email:</span> sales@chalokhelne.com
            </p>
            <p className="text-gray-700">
              <span className="font-semibold">Phone:</span> +91 9272090926
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default LTerms_Conditions;